service: auto-job

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: false

package:
  exclude:
    - node_modules
    - layers
    - events

layers:
  common:
    path: layers/common
    compatibleRuntimes:
      - nodejs12.x

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    TRIGGER_QUEUE_URL: { Ref: JobEventQueue }
    SCRAPE_QUEUE_URL: { Ref: JobDetailQueue }
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - Fn::GetAtt: [JobEventQueue, Arn]
        - Fn::GetAtt: [JobDetailQueue, Arn]
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - Fn::GetAtt: [JobTable, Arn]

functions:
  trigger:
    handler: src/handler/trigger/index.handler
    layers:
      - { Ref: CommonLambdaLayer }
    integration: lambda
    events:
      - http:
          path: trigger
          method: post
          integration: lambda
          cors: true

  list:
    handler: src/handler/list/index.handler
    layers:
      - { Ref: CommonLambdaLayer }
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - JobEventQueue
              - Arn
  detail:
    handler: src/handler/detail/index.handler
    layers:
      - { Ref: CommonLambdaLayer }
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - JobDetailQueue
              - Arn

resources:
  Resources:
    JobEventQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: JobEventQueue
    JobDetailQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: JobDetailQueue
    JobTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
